MULTI_ARROW: true
EXPLOSIVE_ARROW: true
TELEPORT_ARROW: true
SPLIT_SHOT: true
TRACK: true
LIFE_STEAL: true
ORE_LOCATOR: true
VEIN_MINER: true
DASH: true
HEALTH: true
FEATHER_FALLING: true
TREE_FELLER: true
REPLENISH_HUNGER: true
EXCAVATE: true
CRITICAL_HIT: true
EXPERIENCE_POPUPS: true
LEVELUP_MESSAGES: true
REMINDER_MESSAGES: true
EXPERIENCE_ACTIONBAR: true
